language: php

sudo: false

php:
 - 5.5
 - 5.6

env:
 - DB=MYSQL CORE_RELEASE=3.5

before_script:
 - composer self-update || true
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit wysiwyg-accordion/tests
